{
 "title": "ForgeRock Reconciliation",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "cloudwatch" },
   { "name": "agg", "label": "Aggregation", "query": "1d" }
  ]
 },
 "panels": [
  { "title": "Latest reconciliations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest Companies Recon",
   "type": "stat",
   "description": "OK = the latest Companies recon was successful",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| fields strcontains(@message, 'RECON_SUCCESS') as passed\n| stats sum(passed) as passed_count",
     "logGroupNames": [
      "/aws/lambda/cwsyn-mapping-chscompany-d2285bc6-eac0-4206-afc1-4086df4a1b4c"
     ],
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "Last Auth Code Recon",
   "type": "stat",
   "description": "OK = the latest Auth Code recon was successful",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| fields strcontains(@message, 'RECON_SUCCESS') as passed\n| stats sum(passed) as passed_count",
     "logGroupNames": [
      "/aws/lambda/cwsyn-mapping-wfauthcode-70eb801d-5c40-48bc-b944-d9318ffac431"
     ],
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "Last Users Recon",
   "type": "stat",
   "description": "OK = the latest Users recon was successful",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| fields strcontains(@message, 'RECON_SUCCESS') as passed\n| stats sum(passed) as passed_count",
     "logGroupNames": [
      "/aws/lambda/cwsyn-mapping-wfuser-3f347cd7-a6a3-496f-be12-34c9d86382e0"
     ],
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "IDM Endpoint Response",
   "type": "stat",
   "description": "OK = the IDM endpoint to check the latest Companies recon status was successful (200)\nFAIL= the IDM endpoint did not return a 200 code)",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| fields strcontains(@message, 'CANNOT_REACH_IDM_ENDPOINT') as failed\n| stats sum(failed) as failed_count",
     "logGroupNames": [
      "/aws/lambda/cwsyn-mapping-chscompany-d2285bc6-eac0-4206-afc1-4086df4a1b4c"
     ],
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "IDM Endpoint Response",
   "type": "stat",
   "description": "OK = the latest Companies recon was successful",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| fields strcontains(@message, 'CANNOT_REACH_IDM_ENDPOINT') as failed\n| stats sum(failed) as failed_count",
     "logGroupNames": [
      "/aws/lambda/cwsyn-mapping-wfauthcode-70eb801d-5c40-48bc-b944-d9318ffac431"
     ],
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "IDM Endpoint Response",
   "type": "stat",
   "description": "OK = the latest Companies recon was successful",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| fields strcontains(@message, 'CANNOT_REACH_IDM_ENDPOINT') as failed\n| stats sum(failed) as failed_count",
     "logGroupNames": [
      "/aws/lambda/cwsyn-mapping-wfuser-3f347cd7-a6a3-496f-be12-34c9d86382e0"
     ],
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "Latest Recons Details (records processed)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Companies last sync record processed success rate",
   "type": "barchart",
   "description": "Success rate of the canary that checks the latest Companies recon processed records.\n \nEvery check is OK if the latest Companies recon has completed with SUCCESS , and the record processing failure rate is less than 30% ",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "dimensions": { "CanaryName": "mapping-chscompany" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Latest Companies Recon records",
   "type": "stat",
   "description": "OK = in the latest check of the last Companies recon, the number of records which failed processing is less than 30% ",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "mapping-chscompany" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Auth Codes last sync record processed success rate",
   "type": "barchart",
   "description": "Success rate of the canary that checks the latest Auth Codes recon processed records.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "targets": [
    {
     "dimensions": { "CanaryName": "mapping-wfauthcode" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Latest Auth codes Recon records",
   "type": "stat",
   "description": "OK = in the latest check of the last Auth Codes recon, the number of records which failed processing is less than 30% ",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "mapping-wfauthcode" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Users last sync record processed success rate",
   "type": "barchart",
   "description": "Success rate of the canary that checks the latest Users recon processed records.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 32 },
   "targets": [
    {
     "dimensions": { "CanaryName": "mapping-wfuser" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Latest User Recon records",
   "type": "stat",
   "description": "OK = in the latest check of the last Users recon, the number of records which failed processing is less than 30% ",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "mapping-wfuser" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Recon Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Companies recon duration check success rate",
   "type": "barchart",
   "description": "Success rate of duration checks for companies recon duration: SUCCESS is when the recon lasts less than the configured threshold (5 mins in DEV,  4 hours in STAGING and LIVE)",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 41 },
   "targets": [
    {
     "dimensions": { "CanaryName": "duration-chscompany" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Last Companies Recon Duration Check",
   "type": "stat",
   "description": "OK = the last Companies reconciliation completed (with either SUCCESS or FAIL) below the duration threshold (5 mins in DEV and 4 hours in STAGING and LIVE)\nFAILS = the last Companies recon lasted more than the duration threshold value",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "duration-chscompany" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Auth Codes recon duration check success rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 49 },
   "targets": [
    {
     "dimensions": { "CanaryName": "duration-wfauthcode" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Auth Codes Recon Duration Check",
   "type": "stat",
   "description": "OK = the last Auth Codes reconciliation completed (with either SUCCESS or FAIL) below the duration threshold (5 mins in DEV and 4 hours in STAGING and LIVE)\nFAILS = the last Auth Codes recon lasted more than the duration threshold value",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "duration-wfauthcode" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Users Recon duration check success rate",
   "type": "barchart",
   "description": "Success rate of the recon duration checks on the Users reconciliations.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 57 },
   "targets": [
    {
     "dimensions": { "CanaryName": "duration-wfuser" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Users Recon Duration Check",
   "type": "stat",
   "description": "OK = the last Users reconciliation completed (with either SUCCESS or FAIL) below the duration threshold (5 mins in DEV and 4 hours in STAGING and LIVE)\n\nFAILS = the last Users recon lasted more than the duration threshold value",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "duration-wfuser" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Cancelled Recons", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Number of Reconciliation Jobs That Have Been Cancelled Today",
   "type": "stat",
   "description": "Number of Reconciliation Jobs That Have Been Cancelled Today (all ACTIVE recons which last more than 5 hours get cancelled automatically) ",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| fields strcontains(@message, 'Recon Cancelled:') as recon_cancelled\n| stats sum(recon_cancelled) as recon_cancelled_count",
     "logGroupNames": [
      "/aws/lambda/cwsyn-fr-cancel-recon-after-e59ffab2-25eb-44fb-ab6d-88eb355612db"
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "Reconciliation Jobs That Have Been Cancelled Today",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 66 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like /Recon Cancelled:/\n| parse \"* * *\" as Time, Cancelled, Name",
     "logGroupNames": [
      "/aws/lambda/cwsyn-fr-cancel-recon-after-e59ffab2-25eb-44fb-ab6d-88eb355612db"
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  }
 ]
}