{
 "title": "ForgeRock Connectors",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Companies connector health check success rate",
   "type": "barchart",
   "description": "The success rate of the healthcheck for the Companies RCS connector",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "CanaryName": "connector-chscompany" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Companies Connector - Latest status",
   "type": "stat",
   "description": "Outcome of the latest connection status of the Companies connector",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "connector-chscompany" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Companies Connector",
   "type": "stat",
   "description": "Number of failed health checks in the last week",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "connector-chscompany" },
     "metricName": "Failed",
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Companies Connector ",
   "type": "stat",
   "description": "Number of 4xx Errors in the last week",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "connector-chscompany" },
     "metricName": "4xx",
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Auth Codes connector health check success rate",
   "type": "barchart",
   "description": "The success rate of the healthcheck for the Auth Codes RCS connector",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "dimensions": { "CanaryName": "connector-wfauthcode" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Auth Codes Connector - Latest status",
   "type": "stat",
   "description": "Outcome of the latest connection status of the Auth Codes connector",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "connector-wfauthcode" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Auth Codes Connector",
   "type": "stat",
   "description": "Number of failed health checks in the last week",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "connector-wfauthcode" },
     "metricName": "Failed",
     "namespace": "CloudWatchSynthetics",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Auth Codes Connector - Number of 4xx Errors",
   "type": "stat",
   "description": "Number of 4xx Errors in the last week",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "connector-wfauthcode" },
     "metricName": "4xx",
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Users connector health check success rate",
   "type": "barchart",
   "description": "The success rate of the healthcheck for the Users RCS connector",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "dimensions": { "CanaryName": "connector-wfuser" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Users Connector - Latest status",
   "type": "stat",
   "description": "Outcome of the latest connection status of the Users connector",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "connector-wfuser" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Users Connector",
   "type": "stat",
   "description": "Number of failed health checks in the last week",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "connector-wfuser" },
     "metricName": "Failed",
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "WebfilingUser Connector - Number of 4xx Errors",
   "type": "stat",
   "description": "Number of 4xx Errors in the last week",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "connector-wfuser" },
     "metricName": "4xx",
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "RCS health check: success rate",
   "type": "barchart",
   "description": "The success rate of the health check for the RCS server",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "dimensions": { "CanaryName": "fr-rcs" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RCS - Latest status",
   "type": "stat",
   "description": "Outcome of the latest connection status of the RCS server",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "fr-rcs" },
     "metricName": "SuccessPercent",
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RCS - Number of failed health checks",
   "type": "stat",
   "description": "Number of RCS weekly failures",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "fr-rcs" },
     "metricName": "Failed",
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "RCS - Number of 4xx Errors",
   "type": "stat",
   "description": "Number of 4xx Errors in the last week",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CanaryName": "fr-rcs" },
     "metricName": "4xx",
     "namespace": "CloudWatchSynthetics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  }
 ]
}