{
 "title": "IDM Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Self-Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 } },
  {
   "title": "Self-Service Registration Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(idm_selfservice_user_registration_count)"
    }
   ]
  },
  {
   "title": "Self-Service Password Reset Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(idm_selfservice_user_password_reset_count)"
    }
   ]
  },
  { "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 } },
  {
   "title": "Registration Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(idm_selfservice_user_registration_count[1m]))",
     "legendFormat": "m1_rate "
    },
    {
     "expr": "sum(rate(idm_selfservice_user_registration_count[5m]))",
     "legendFormat": "m5_rate "
    },
    {
     "expr": "sum(rate(idm_selfservice_user_registration_count[15m]))",
     "legendFormat": "m15_rate "
    }
   ]
  },
  {
   "title": "User Password Rest Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(idm_selfservice_user_password_reset_count[1m]))",
     "legendFormat": "m1_rate "
    },
    {
     "expr": "sum(rate(idm_selfservice_user_password_reset_count[5m]))",
     "legendFormat": "m5_rate "
    },
    {
     "expr": "sum(rate(idm_selfservice_user_password_reset_count[15m]))",
     "legendFormat": "m15_rate "
    }
   ]
  },
  { "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 } },
  {
   "title": "Self-Service User Login Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(idm_user_login_total)" }
   ]
  },
  {
   "title": "Login Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(am_authentication_count{job=\"AM\"}[15m]))",
     "legendFormat": "m15_rate"
    }
   ]
  },
  { "title": "Managed Object Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Managed User Median",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "idm_managed_seconds{job=\"IDM\",managed_object=\"alpha_user\",quantile=\"0.5\"}",
     "legendFormat": "{{operation}} "
    }
   ]
  },
  {
   "title": "Managed Role Median",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "idm_managed_seconds{job=\"IDM\",managed_object=\"alpha_role\",quantile=\"0.5\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Managed Object Average",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(idm_managed_count{managed_object=\"alpha_role\"}[15m]))",
     "legendFormat": "role  m15_rate"
    },
    {
     "expr": "sum(rate(idm_managed_count{managed_object=\"alpha_role\"}[1m]))",
     "legendFormat": "role m1_rate"
    },
    {
     "expr": "sum(rate(idm_managed_count{managed_object=\"alpha_user\"}[15m]))",
     "legendFormat": "user m15_rate"
    },
    {
     "expr": "sum(rate(idm_managed_count{managed_object=\"user\"}[1m]))",
     "legendFormat": "user m1_rate"
    }
   ]
  },
  { "title": "Sync Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Sync Object Mapping Median",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "idm_sync_objectmapping_seconds{quantile=\"0.5\"}",
     "legendFormat": "{{mapping_name}} "
    }
   ]
  },
  {
   "title": "Sync Average",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "ops", "label": "calls/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(idm_sync_objectmapping_count[1m]))",
     "legendFormat": "sync m1_rate"
    },
    {
     "expr": "sum(rate(idm_sync_objectmapping_count[5m]))",
     "legendFormat": "sync m5_rate"
    },
    {
     "expr": "sum(rate(idm_sync_objectmapping_count[15m]))",
     "legendFormat": "sync m15_rate"
    }
   ]
  },
  { "title": "Recon Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Recon Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "sum(rate(idm_recon_count[1m]))", "legendFormat": "m1_rate" },
    { "expr": "sum(rate(idm_recon_count[5m]))", "legendFormat": "m5_rate" },
    {
     "expr": "sum(rate(idm_recon_count[15m]))",
     "legendFormat": "m15_rate"
    }
   ]
  },
  { "title": "Repo Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Repo Median",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(idm_repo_seconds{quantile=\"0.5\", operation=\"create\"})",
     "legendFormat": "create "
    },
    {
     "expr": "sum(idm_repo_seconds{quantile=\"0.5\", operation=\"read\"})",
     "legendFormat": "read"
    },
    {
     "expr": "sum(idm_repo_seconds{quantile=\"0.5\", operation=\"update\"})",
     "legendFormat": "update"
    },
    {
     "expr": "sum(idm_repo_seconds{quantile=\"0.5\", operation=\"delete\"})",
     "legendFormat": "delete"
    },
    {
     "expr": "sum(idm_repo_seconds{quantile=\"0.5\", operation=\"patch\"})",
     "legendFormat": "patch"
    },
    {
     "expr": "sum(idm_repo_seconds{quantile=\"0.5\", operation=\"action\"})",
     "legendFormat": "action"
    },
    {
     "expr": "sum(idm_repo_seconds{quantile=\"0.5\", operation=\"query\"})",
     "legendFormat": "query"
    }
   ]
  },
  {
   "title": "Repo Average",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(idm_repo_count{operation=\"create\"}[5m]))",
     "legendFormat": "create m5_rate"
    },
    {
     "expr": "sum(rate(idm_repo_count{operation=\"read\"}[5m]))",
     "legendFormat": "read m5_rate"
    },
    {
     "expr": "sum(rate(idm_repo_count{operation=\"update\"}[5m]))",
     "legendFormat": "update m5_rate"
    },
    {
     "expr": "sum(rate(idm_repo_count{operation=\"delete\"}[5m]))",
     "legendFormat": "delete m5_rate"
    },
    {
     "expr": "sum(rate(idm_repo_count{operation=\"patch\"}[5m]))",
     "legendFormat": "patch m5_rate"
    },
    {
     "expr": "sum(rate(idm_repo_count{operation=\"action\"}[5m]))",
     "legendFormat": "action m5_rate"
    },
    {
     "expr": "sum(rate(idm_repo_count{operation=\"query\"}[5m]))",
     "legendFormat": "query m5_rate"
    }
   ]
  },
  { "title": "Audit Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Audit Average",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "ops", "label": "events/sec" }
   ],
   "targets": [
    { "expr": "sum(rate(idm_audit_count[5m]))", "legendFormat": "{{audit_topic}} m5_rate" }
   ]
  }
 ]
}